# local, dev, prod 공통 설정
server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 1800


mybatis:
  type-aliases-package: com.knpharm.knadmin.dto
  mapper-locations: mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

# Thymleaf
spring:
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

---
spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      location: "C:\\upload"
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/knpharm?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: master
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false # 개발시에는 수정시 즉시 반영 가능하게.
naver:
  url:
    geocoding: https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode
  client:
    id: l2o6xz5abj
    secret: 3ulkg7WHEZuhYYTysTOkg44xHv7iCqHHfJO8Hgu1
server:
  port: 88

---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      location: "/data/upload/dev"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kntest?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: kndev
    password: dev@w2w
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false # 개발시에는 수정시 즉시 반영 가능하게.
naver:
  url:
    geocoding: https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode
  client:
    id: l2o6xz5abj
    secret: 3ulkg7WHEZuhYYTysTOkg44xHv7iCqHHfJO8Hgu1
server:
  port: 8073
  error:
    include-exception: true
    include-stacktrace: always
---
spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      location: "/data/upload/prod"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knpharm?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: knadmin
    password: kn@w2w
  thymeleaf:
    cache: true
naver:
  url:
    geocoding: https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode
  client:
    id: bsj7qymjt7
    secret: DdeJ5OJrizJcL6SOPW6M3KNnmohmnBzZie0IVlOX
server:
  port: 8083